### PR TITLE
use 2-d std::array instead of vector + index math

### PR DESCRIPTION
**Pull request by dscottboggs**
I saw your video last night, and I thought it was very entertaining, but there was something that bothered me -- your use of a `vector` to store a 2-d array whose size is known at compile-time (I.E. `constexpr`), especially considering your comment about not using a vector of vectors. It seemed to me like you might not have understood *why* people suggested you not use a vector of vectors and, given that the size of the matrix is known at compile time, a way you could keep your 2-d interface.

A `std::vector` is something along the lines of a struct like this

```c++
template<typename T>
struct pseudo_vector {
  size_t len;
  size_t cap;
  T* buffer;

  pseudo_vector() : len(0), cap(DEFAULT_CAP) {
    this->buffer = new T[DEFAULT_CAP];
  }
}
```

Because the size isn't known at compile-time, the buffer backing the dataset is *dynamically allocated* (i.e. with the `new[]` operator). Then, when `push_back` or some other method which can grow the buffer is called, it may reallocate the buffer if the action would grow the dataset beyond the buffer size (`cap * sizeof(T)`).

This means that when you take a `vector<vector<T>>`, you're really only *contiguously* storing the pointers to a bunch of dynamically allocated buffers, which may be scattered anywhere throughout memory. Because the memory is more sparsely laid out, you lose performance doing memory lookups and increase your chances of a cache miss.

Alternatively, with a `std::array<std::array<T, COLUMNS>, ROWS>` (or the equivalent `T[COLUMNS][ROWS]` static array from C), you're physically storing a buffer that's `sizeof(T * COLUMNS * ROWS)` on the stack, where all cells are stored contiguously, just like with your initial implementation, but while also keeping the nice 2-d matrix interface (`cells[x_coord][y_coord]`).

---

Since you didn't include build instructions, I don't know if this will compile, but hopefully you get what I mean by this.

### CODE REVIEW

**Comment by Kofybrek** [comment]
Well, I did say in my video that I'm a PROFESSIONAL!

But seriously, you're right! This is better than using GetCell. I'll be using it in my next project.

Thanks!

**Comment by crumblingstatue** [comment]
The project doesn't seem to be building after this pull request got merged. It has multiple errors, including things like referring to a header file that was deleted.

**Comment by crumblingstatue** [comment]
> Since you didn't include build instructions, I don't know if this will compile, but hopefully you get what I mean by this.

Looks like this pull request wasn't even tested if it compiles, let alone if it works. it was only meant to show their idea.
I suggest reverting this commit because it makes the game unable to compile.
I worked on fixing the build, but when I ran the game it seems like the logic is messed up too, so I would recommend reverting this commit.

**Comment by Kofybrek** [comment]
Damn! Thanks for telling me this!

**Pull request merged**
